### ISSUE TITLE
typing.Protocol is better candidate for base serialization classes.

### ISSUE THREAD

**Issue by PradyumnaKrishna** [in-toto/securesystemslib#10]
**Description of issue or feature request**:
The following classes of serialization module would be better candidates for `typing.Protocol` than `abc`:
- `BaseSerializer`
- `BaseDeserializer`
- `JSONSerializable`

`typing.Protocol` requires python version 3.8 and above and hence this couldn't be done now.
After dropping support of python 3.7 by securesystemslib these classes should use `typing.Protocol`.

**Current Behaviour**
Mentioned classes are abstract base class in serialization module.

**Expected behavior**:
Mentioned classes should be `typing.Protocol`.

_Originally posted by @lukpueh in https://github.com/in-toto/securesystemslib/pull/9#pullrequestreview-1071090292_

**Comment by adityasaky** [comment]
Can we track this in the upstream securesystemslib repository instead of here?

**Comment by lukpueh** [comment]
I think I am in favor of just closing this issue:
- using Protocol does not improve user/developer experience significantly enough to justify using a backport for Python 3.7 now, or a refactor after dropping 3.7
 
- @jku  raised valid [concerns about lack of declaration](https://github.com/secure-systems-lab/securesystemslib/issues/463#issuecomment-1330408890) in classes that implement a Protocol
