### ISSUE TITLE
Exception handling on Key.verify for incompatible type of signature

### ISSUE THREAD

**Issue by PradyumnaKrishna** [in-toto/securesystemslib#8]
**Description of issue or feature request**:
`Key.verify` method can produce unknown error's during verification of signatures. Example: If a `GPGKey` is used to verify a signature of type `Signature`, will cause a FormatError. With `FormatError` determining the cause of error is not easy.
`Key.verify` method should handle these exceptions and raise exceptions for different causes.

**Current behavior**:
No error handling in `Key.verify`.

**Expected behavior**:
Error handling should be added to `Key.verify`.

Ref: https://github.com/in-toto/securesystemslib/pull/2#discussion_r926370516

**Comment by lukpueh** [comment]
TLDR https://github.com/in-toto/securesystemslib/pull/2#discussion_r926370516: Change `Key.verify` to return None on success and raise error otherwise.

**Comment by lukpueh** [comment]
Fixed upstream in https://github.com/secure-systems-lab/securesystemslib/pull/456, see [`signer.Key.verify_signature`](https://github.com/jku/securesystemslib/blob/10edc1a3112315b44d4b20bef0b00c401398f18a/securesystemslib/signer/_key.py#L106-L119).
